---
- name: CLICKHOUSE | Ensure clickhouse group
  ansible.builtin.group:
    name: "{{ clickhouse_group }}"
    system: yes
    state: present
  tags: [clickhouse_install]

- name: CLICKHOUSE | Ensure clickhouse user
  ansible.builtin.user:
    name: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no
  tags: [clickhouse_install]

- name: CLICKHOUSE | Ensure base directory exist
  ansible.builtin.file:
    state: directory
    dest: "{{ clickhouse_data_dir }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "{{ clickhouse_base_directory_mode }}"
  become: true
  tags: [clickhouse_install]

- name: Add ClickHouse repository key
  ansible.builtin.apt_key:
    url: "{{ clickhouse_key_url }}"
    state: present
  tags: [clickhouse_install]

- name: Add ClickHouse repository
  ansible.builtin.apt_repository:
    repo: "{{ clickhouse_deb_repo }}"
    state: present
    update_cache: yes
  tags: [clickhouse_install]

- name: Install ClickHouse server and client
  ansible.builtin.apt:
    name: "{{ clickhouse_packages }}"
    state: present
    update_cache: yes
  tags: [clickhouse_install]

- name: Create ClickHouse configuration directory
  become: true
  file:
    path: "{{ clickhouse_config_path }}"
    state: directory
    owner: clickhouse
    group: clickhouse
    mode: "0755"
  tags: [clickhouse_install]

- name: Deploy ClickHouse configuration
  become: true
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_config_path }}/config.xml"
    owner: clickhouse
    group: clickhouse
    mode: "0644"
  notify: "{{ clickhouse_handler_on_config_change }}"
  tags: [clickhouse_install]

# - name: Deploy ClickHouse user configuration
#   become: true
#   template:
#     src: user.xml.j2
#     dest: "{{ clickhouse_config_path }}/user.xml"
#     owner: clickhouse
#     group: clickhouse
#     mode: "0644"
#   notify: "{{ clickhouse_handler_on_config_change }}"
#   tags: [clickhouse_install]

- name: Ensure ClickHouse data directory exists
  become: true
  file:
    path: "{{ clickhouse_data_dir }}"
    state: directory
    owner: clickhouse
    group: clickhouse
    mode: "0755"
  tags: [clickhouse_install]

- name: Ensure ClickHouse log directory exists
  become: true
  file:
    path: "{{ clickhouse_log_dir }}"
    state: directory
    owner: clickhouse
    group: clickhouse
    mode: "0755"
  tags: [clickhouse_install]

- name: Start and enable ClickHouse service
  become: true
  service:
    name: clickhouse-server
    state: started
    enabled: true
  tags: [clickhouse_install]
