# - name: Install denpendencies
#   apt:
#     name: apt-transport-https
#     state: present

# - name: Add Grafana APT repository
#   apt_repository:
#     repo: deb https://packages.grafana.com/oss/release/deb stable main
#     state: present
#     filename: grafana
#     update_cache: yes

# - name: Install Grafana
#   apt:
#     name: grafana={{ grafana_version }}
#     state: present

# - name: Enable and Start Grafana service
#   service:
#     name: grafana-server
#     state: started
#     enabled: yes


---
  - name: Add Grafana repository key
    ansible.builtin.apt_key:
      url: "{{ grafana_repo_key }}"
      state: present
    tags: [grafana_install]

  - name: Add Grafana repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] {{ grafana_repo_url }}"
      state: present
      update_cache: yes
    tags: [grafana_install]

  - name: Install Grafana
    become: true
    apt:
      name: "{{ grafana_package_name }}={{ grafana_version }}*"
      state: present
      update_cache: yes
    tags: [grafana_install]

  - name: Start and enable Grafana service
    become: true
    service:
      name: grafana-server
      state: "{{ grafana_service_state }}"
      enabled: "{{ grafana_service_enabled }}"
    tags: [grafana_install]

  # --- Grafana provisioning automation ---
  - name: Create Grafana provisioning directories
    become: true
    file:
      path: /etc/grafana/provisioning/datasources
      state: directory
      mode: '0755'

  - name: Provision ClickHouse datasource
    become: true
    copy:
      dest: /etc/grafana/provisioning/datasources/clickhouse-datasource.yml
      content: |
        apiVersion: 1
        datasources:
          - name: ClickHouse
            type: vertamedia-clickhouse-datasource
            access: proxy
            url: http://localhost:8123
            basicAuth: false
            isDefault: true
            editable: true

  - name: Restart Grafana service after provisioning
    become: true
    service:
      name: grafana-server
      state: restarted