---
# Ensure necessary dependencies is installed
  - name: Ensure wget is installed
    become: true
    apt:
      name: wget
      state: present
      update_cache: yes

############## End Dependencies ######################

# - name: Add OpenTelemetry Collector GPG key
#   become: true
#   ansible.builtin.apt_key:
#     url: https://packages.signalfx.com/otel-collector/gpgkey
#     state: present
#   tags: [otel_install]

# - name: Add OpenTelemetry Collector repository
#   become: true
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=amd64] https://packages.signalfx.com/otel-collector/apt stable main"
#     state: present
#     update_cache: yes
#   tags: [otel_install]

# - name: Install OpenTelemetry Collector
#   become: true
#   ansible.builtin.apt:
#     name: opentelemetry-collector
#     state: present
#   tags: [otel_install]

  - name: Install OpenTelemetry Collector
    ansible.builtin.include_role:
      name: grafana.grafana.opentelemetry_collector
