---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

      
- name: Install required packages
  package:
    name:
      - gpg
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
      - wget
    state: present
    update_cache: yes